name: Auto Label PR

on:
  issues:
    types:
      - labeled
      - unlabeled
  # pull_request:
  #   types:
  #     - opened
  #     - edited
  push:
    branches:
      - auto-label-pr

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          owner=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
          repo=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)

          prNumber=$(gh api graphql --jq '.data.repository.issue.timelineItems.nodes.[] | .source.number' -f query='
            query {
              repository(owner: "ofirl", name: "SpeakStick") {
                # ${{ github.event.issue.number }}
                issue(number: 31) {
                  labels {
                    nodes {
                      name
                    }
                  }
                  timelineItems(first: 100) {
                    nodes {
                      ... on CrossReferencedEvent {
                        source {
                          ... on PullRequest {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ' | grep -v -e '^$')

          # --jq '.data.repository.issue.labels.nodes.[] | .name'
          labels=$(gh api graphql -f query='
            query {
              repository(owner: "ofirl", name: "SpeakStick") {
                # ${{ github.event.issue.number }}
                issue(number: 31) {
                  labels(first: 100) {
                    nodes {
                      name
                    }
                  }
                }
              }
            }
          ')

          echo $labels
        env:
          GITHUB_TOKEN: ${{ github.token }}
