name: Auto Label PR

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - auto-label-pr

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Issue updated"
        if: ${{ github.event_name == 'issues' }}
        run: |
          owner=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
          repo=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)

          prNumber=$(gh api graphql --jq '.data.repository.issue.timelineItems.nodes.[] | .source.number' -f query='
            query {
              repository(owner: "ofirl", name: "SpeakStick") {
                # ${{ github.event.issue.number }}
                issue(number: 31) {
                  timelineItems(first: 100) {
                    nodes {
                      ... on CrossReferencedEvent {
                        source {
                          ... on PullRequest {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ' | grep -v -e '^$')
          echo $prNumber

          if ${{ github.event.action == 'labeled' }}
          then
            gh pr edit $prNumber --add-label ${{ github.event.label }}
          else
            gh pr edit $prNumber --remove-label ${{ github.event.label }}
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "PR updated"
        # if: ${{ github.event_name == 'pull_request' }}
        run: |
          owner=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
          repo=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)

          issueLabels=$(gh api graphql --jq '.data.repository.pullRequest.closingIssuesReferences.edges | map(.node.number)' -f query='
            query {
              repository(owner: "ofirl", name: "SpeakStick") {
                # ${{ github.event.number }}
                pullRequest(number: 33) {
                  closingIssuesReferences (first: 50) {
                    edges {
                      node {
                        number
                      }
                    }
                  }
                }
              }
            }
          ' | grep -v -e '^$')
          echo $issueLabels

          # issueLabels=$(gh api graphql --jq '.data.repository.issue.labels.nodes | map(.name) | join(",")' -f query='
          #   query {
          #     repository(owner: "ofirl", name: "SpeakStick") {
          #       # ${{ github.event.issue.number }}
          #       issue(number: 31) {
          #         labels(first: 100) {
          #           nodes {
          #             name
          #           }
          #         }
          #       }
          #     }
          #   }
          # ')
          # echo $issueLabels

          # gh pr edit ${{ github.event.number }} --add-label $issueLabels
        env:
          GITHUB_TOKEN: ${{ github.token }}
