name: PR Auto Labeler

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request:
    types:
      - opened
      - edited

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Issue updated"
        if: ${{ github.event_name == 'issues' }}
        run: |
          prNumber=$(gh api graphql --jq '.data.repository.issue.timelineItems.nodes.[] | .source.number' -f query='
            query {
              repository(owner: "ofirl", name: "SpeakStick") {
                # ${{ github.event.issue.number }}
                issue(number: 31) {
                  timelineItems(first: 100) {
                    nodes {
                      ... on CrossReferencedEvent {
                        source {
                          ... on PullRequest {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ' | grep -v -e '^$')
          echo $prNumber

          if ${{ github.event.action == 'labeled' }}
          then
            gh pr edit $prNumber --add-label ${{ github.event.label.name }}
          else
            gh pr edit $prNumber --remove-label ${{ github.event.label.name }}
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "PR updated"
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          issueLabels=$(gh api graphql --jq '.data.repository.pullRequest.closingIssuesReferences.edges[].node.labels.nodes | map(.name) | join(",")' -f query='
            query {
              repository(owner: "ofirl", name: "SpeakStick") {
                pullRequest(number: ${{ github.event.number }}) {
                  closingIssuesReferences (first: 50) {
                    edges {
                      node {
                        number
                        labels(first: 100) {
                          nodes {
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ')
          echo $issueLabels

          if [ -z "$issueLabels" ]
          then
            echo "no labels found"
          else
            for label in $issueLabels
            do
              gh pr edit ${{ github.event.number }} --add-label $label
            done
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
