name: Build and Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  bild_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build Management Console
        run: |
          npm install -g pnpm
          cd management-console
          pnpm install
          pnpm run build
          zip -r dist/management-console.zip dist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
          files: |
            management-console/dist/management-console.zip

      - name: Set Release URL
        run: echo "[${{ inputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ inputs.tag }})" >> $GITHUB_STEP_SUMMARY
