name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build_and_release:
    uses: ofirl/SpeakStick/.github/workflows/build_and_release.yml@master
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
