name: Create Tag

on:
  push:
    branches:
      - fix-workflow-errors

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.increment_version.outputs.new_tag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          git --version

          echo "tags"
          git tag -l
          echo "tags sorted"
          git tag -l --sort=-v:refname
          echo "first sorted tags"
          git tag -l --sort=-v:refname | head -n 1

          latest_tag=$(git tag -l --sort=-v:refname | head -n 1)
          echo "$latest_tag"

          # latest_tag=$(echo "$latest_tag" | tr -d '\n')
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "latest_tag=`${latest_tag}`" >> $GITHUB_STEP_SUMMARY

      - name: Increment Minor Version
        id: increment_version
        run: |
          tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          IFS='.' read -ra version_parts <<< "$tag"
          minor_version=$((version_parts[1] + 1))
          new_tag="${version_parts[0]}.${minor_version}.0"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          echo "new_tag=`$new_tag`" >> $GITHUB_STEP_SUMMARY
